### ISSUE TITLE
Error while compiling rpki tools 

### ISSUE THREAD

**Issue by fendemann** [dragonresearch/rpki.net#849]
Starting with a fresh ubuntu 16.04 server I get the following error, when I try to build the rpki tools:

$ /configure --disable-ca-tools
... 
$ make
/usr/bin/python buildtools/make-version.py
Could not determine software version
Makefile:128: recipe for target 'VERSION' failed
make: *** [VERSION] Error 1

Here are the steps made before:

$ sudo apt-get dist-upgrade
$ sudo su
$ sudo wget -q -O /etc/apt/trusted.gpg.d/rpki.asc   https://download.rpki.net/APTng/apt-gpg-key.asc
$ sudo wget -q -O /etc/apt/sources.list.d/rpki.list https://download.rpki.net/APTng/rpki.xenial.list
$ sudo apt-get update
$ sudo apt-get install rpki-rp
$ mkdir Downloads
$ cd Downloads/
$ sudo apt-get install subversion build-essential rrdtool xsltproc python2.7 python-vobject libyaml-dev libpython2.7-dev python-pip python-django python-lxml python-tornado
$ sudo pip install pyyaml
$ svn co https://github.com/dragonresearch/rpki.net.git/trunk rpki-src
$ cd rpki-src/

**Comment by sraustein** [comment]
`make-version.py` is looking for a git environment, not subversion.

**Comment by fendemann** [comment]
Using a git environment I was able to build the tools.
I think it is confusing when using the <i>Clone or download</i> button to get the software. It gives the option to download via git or svn.
Thx
