### ISSUE TITLE
rpkic command to delete resources or objects

### ISSUE THREAD

**Issue by fendemann** [dragonresearch/rpki.net#851]
I try to delete a resource via rpkic (roa with prefix for ipv6) but I cannot find a usefull command. 
Using the GUI does not work, see #850

**Comment by sraustein** [comment]
Create a csv file with all the ROA requests except the one(s) you want to delete, then load that with `rpkic load_roa_requests`.

**Comment by fendemann** [comment]
Works, thx.
Playing around with _**rpkic load_roa_requests**_  I found out some interessting behavior:

-------- CASE 1 --------
**_more roas_play.csv 
49.10.0.0/24 4910 LAB-DTAG
2049:10:64::/48 4910 LAB-DTAG_**

Import the above csv results in **one** roa and only the ipv4 prefix shown in the GUI.

**_sudo rpkic show_published_objects
rsync://rpki-root-01.lab.dtag.de/rpki/LAB-DTAG/aL43YCvA_Ke0cKim-Hqx_O-Cbp0.crl 2017-01-10T19:30:58Z 8FB9A4EF610DB95B28438758B5C1D2EFE56A5B06
rsync://rpki-root-01.lab.dtag.de/rpki/LAB-DTAG/aL43YCvA_Ke0cKim-Hqx_O-Cbp0.mft 2017-01-10T19:30:58Z 7E03C3503E15FEA798B0FD18B8641DE80CAE36C0
rsync://rpki-root-01.lab.dtag.de/rpki/LAB-DTAG/e5PSzhDRngV5Z118mqmXn9iNVLU.roa 2017-01-10T19:30:58Z 3ED3DA3623A7D91AC644A33555F2CF9253FAE710 4910 2049:10:64::/48,49.10.0.0/24_**

-------- CASE 2 --------
**_more roas_play.csv 
2049:10:64::/48 4910 LAB-DTAG-0
49.10.0.0/24 4910 LAB-DTAG-1_**

Exporting the roas via the GUI create the above file. Re-import the file results in **two** roas. Both, the IPv4 and IPv6 prefix are shown in the GUI.


**_sudo rpkic show_published_objects
rsync://rpki-root-01.lab.dtag.de/rpki/LAB-DTAG/aL43YCvA_Ke0cKim-Hqx_O-Cbp0.crl 2017-01-10T19:42:43Z 593BFC39DBBA7C7D8DC10D9CA5F83B70D80CAED7
rsync://rpki-root-01.lab.dtag.de/rpki/LAB-DTAG/aL43YCvA_Ke0cKim-Hqx_O-Cbp0.mft 2017-01-10T19:42:43Z 428525973312D5B3C8D406C706AAA8A1653CBBFA
rsync://rpki-root-01.lab.dtag.de/rpki/LAB-DTAG/N0cwlp_GpKJcGFB6NpfsfG6ffUw.roa 2017-01-10T19:42:43Z 11830C1F9FD817333986B480FB5F657482DFF377 4910 2049:10:64::/48
rsync://rpki-root-01.lab.dtag.de/rpki/LAB-DTAG/ZIyJh_9FNy8lgTicd3Ec_c_d_I0.roa 2017-01-10T19:42:43Z 30573C1202B6DC0CF84DC40F1CD8F3DE4419D94E 4910 49.10.0.0/24_**

Is this a normal behavior ??

**Comment by sraustein** [comment]
Yes, this is normal.  `rpkic` supports forcing multiple prefixes into a single ROA, the GUI does not.  Using the same label (`LAB-DTAG`) for multiple ROA requests with the same ASN in the first example is requesting that they be bundled into a single ROA.  The second example uses different tags, so gets separate ROAs.  Omitting the tag entirely is equivalent to using a unique tag on each line, ie, all separate ROAs.

**Comment by fendemann** [comment]
OK. Last question for this evening ;-)

What about prefix ranges, how do I import them??
In 2014 we`ve imported a range like 185.142.142.0/23^23-24.

Trying this with the csv file results in

**_sudo rpkic load_roa_requests roas_play.csv 
Traceback (most recent call last):
  File "/usr/sbin/rpkic", line 57, in <module>
    rpki.rpkic.main()
  File "/usr/lib/python2.7/dist-packages/rpki/rpkic.py", line 129, in __init__
    self.main(args)
  File "/usr/lib/python2.7/dist-packages/rpki/rpkic.py", line 136, in main
    args.func(self, args)
  File "/usr/lib/python2.7/dist-packages/rpki/rpkic.py", line 764, in do_load_roa_requests
    self.zoo.load_roa_requests(f)
  File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rpki/irdb/zookeeper.py", line 1042, in load_roa_requests
    p = rpki.resource_set.roa_prefix_ipv4.parse_str(pnm)
  File "/usr/lib/python2.7/dist-packages/rpki/resource_set.py", line 933, in parse_str
    raise rpki.exceptions.BadROAPrefix('Bad ROA prefix "%s"' % x)
rpki.exceptions.BadROAPrefix: Bad ROA prefix "194.45.148.0/22^22-24"_**

**Comment by sraustein** [comment]
We've never supported the RPSL prefix range syntax.  If you want a bunch of prefixes, you'll have to list them, although presumably one could write a tool to generate the expansion from the RPSL syntax.

**Comment by fendemann** [comment]
Ok, but I´ll not be the guy to write this tool.
Thx.
