### ISSUE TITLE
errors doing 'rpkic configure_root'

### ISSUE THREAD

**Issue by jayb-github** [dragonresearch/rpki.net#857]
I was following the recently revised instructions at https://github.com/dragonresearch/rpki.net/blob/master/doc/quickstart/xenial-ca.md 
All went well until I attempted to execute 'rpkic configure_root', at which point the following occurred:

# rpkic configure_root
Generating root for resources ASN: 0-4294967295, V4: 0.0.0.0/0, V6: ::/0
Traceback (most recent call last):
  File "/usr/sbin/rpkic", line 57, in <module>
    rpki.rpkic.main()
  File "/usr/lib/python2.7/dist-packages/rpki/rpkic.py", line 129, in __init__
    self.main(args)
  File "/usr/lib/python2.7/dist-packages/rpki/rpkic.py", line 136, in main
    args.func(self, args)
  File "/usr/lib/python2.7/dist-packages/rpki/rpkic.py", line 429, in do_configure_root
    r = self.zoo.configure_root(args.root_handle, args.resources)
  File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rpki/irdb/zookeeper.py", line 371, in configure_root
    issuer          = self.resource_ca,
  File "/usr/lib/python2.7/dist-packages/rpki/irdb/zookeeper.py", line 273, in resource_ca
    return rpki.irdb.models.ResourceHolderCA.objects.get(handle = self.handle)
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
rpki.irdb.models.DoesNotExist: ResourceHolderCA matching query does not exist.
#

**Comment by sraustein** [comment]
I was not able to reproduce this, but I have a guess as to what triggered it.

```
sra@penguinista:~$ fgrep handle /etc/rpki.conf
handle = penguinista_test_hactrn_net

sra@penguinista:~$ rpkic

rpkic> create_identity penguinista_test_hactrn_net
Wrote /home/sra/penguinista_test_hactrn_net.identity.xml
This is the "identity" file you will need to send to your parent

rpkic> select_identity penguinista_test_hactrn_net
rpkic> configure_root 
Generating root for resources ASN: 0-4294967295, V4: 0.0.0.0/0, V6: ::/0
Wrote /home/sra/penguinista_test_hactrn_net.penguinista_test_hactrn_net.repository-request.xml
This is the file to send to the repository operator

rpkic> configure_publication_client penguinista_test_hactrn_net.penguinista_test_hactrn_net.repository-request.xml
This might be an offer, checking
We don't host this client's parent, so we didn't make an offer
Don't know where else to nest this client, so defaulting to top-level
Client calls itself 'penguinista_test_hactrn_net', we call it 'penguinista_test_hactrn_net'
Wrote /home/sra/penguinista_test_hactrn_net.repository-response.xml
Send this file back to the publication client you just configured

rpkic> configure_repository penguinista_test_hactrn_net.repository-response.xml 
Repository calls us 'penguinista_test_hactrn_net'
No explicit parent_handle given, guessing parent penguinista_test_hactrn_net
```

My guess is that the trigger was (somehow) having the wrong rpkic identity name selected when you issued the `configure_root` command.  If you're using rpkic's own command processor, you can use the `select_identity` command with tab completion to select a valid entity name.  As stated in Randy's quickstart guide, the default identity name if you haven't selected one is the "handle" value from rpki.conf, but that's just a default.

Either that or somehow creating a relationship with a normal parent somehow poisons root configuration, I haven't set up a test for that (yet).

**Comment by sraustein** [comment]
Still can't reproduce:

```
rpkic> create_identity Alice
Wrote /home/sra/Alice.identity.xml
This is the "identity" file you will need to send to your parent

rpkic> select_identity penguinista_test_hactrn_net

rpkic> configure_child Alice.identity.xml 
Child calls itself 'Alice', we call it 'Alice'
Wrote /home/sra/penguinista_test_hactrn_net.Alice.parent-response.xml
Send this file back to the child you just configured

rpkic> select_identity Alice

rpkic> configure_parent penguinista_test_hactrn_net.Alice.parent-response.xml 
Parent calls itself 'penguinista_test_hactrn_net', we call it 'penguinista_test_hactrn_net'
Parent calls us 'Alice'
Wrote /home/sra/Alice.penguinista_test_hactrn_net.repository-request.xml
This is the file to send to the repository operator

rpkic> select_identity penguinista_test_hactrn_net

rpkic> configure_publication_client Alice.penguinista_test_hactrn_net.repository-request.xml 
This might be an offer, checking
Found client and its parent, nesting
Client calls itself 'Alice', we call it 'penguinista_test_hactrn_net/Alice'
Wrote /home/sra/penguinista_test_hactrn_net.Alice.repository-response.xml
Send this file back to the publication client you just configured

rpkic> select_identity Alice

rpkic> configure_repository penguinista_test_hactrn_net.Alice.repository-response.xml 
Repository calls us 'penguinista_test_hactrn_net/Alice'
No explicit parent_handle given, guessing parent penguinista_test_hactrn_net

rpkic> configure_root 
Generating root for resources ASN: 0-4294967295, V4: 0.0.0.0/0, V6: ::/0
Wrote /home/sra/Alice.Alice.repository-request.xml
This is the file to send to the repository operator

rpkic> configure_rpkic> select_identity penguinista_test_hactrn_net

rpkic> configure_publication_client Alice.Alice.repository-request.xml 
This might be an offer, checking
Found client and its parent, nesting
Client calls itself 'Alice', we call it 'penguinista_test_hactrn_net/Alice'
Wrote /home/sra/penguinista_test_hactrn_net.Alice.repository-response.xml
Send this file back to the publication client you just configured

rpkic> select_identity Alice

rpkic> configure_repository penguinista_test_hactrn_net.Alice.repository-response.xml 
Repository calls us 'penguinista_test_hactrn_net/Alice'
No explicit parent_handle given, guessing parent Alice
```

If the problem were just that one can't have a normal parent and a root in the same entity, I would have expected Alice's `configure_root` to fail.

**Comment by jayb-github** [comment]
closing issue, ascribing the initial errors to problems happening on the underlying hypervisor.
