### ISSUE TITLE
rcynic-cron, rcynic daemon won't start

### ISSUE THREAD

**Issue by shappleberry** [dragonresearch/rpki.net#865]
I downloaded packages and the following two daemons won't start: 

rpki     28547  0.0  0.3  25356  7108 ?        Ss   06:36   0:00 /usr/bin/python /usr/bin/rcynic-cron
rpki     28548 13.5  4.6 268756 94456 ?        S    06:36   0:55 /usr/bin/python /usr/bin/rcynic

**Comment by sraustein** [comment]
Sorry, never saw a notification for this from GitHub.

rcynic isn't a daemon, exactly, it normally runs under cron, specifically under rcynic-cron which runs it and several other programs at some randomly-chosen minute every hour.
