### ISSUE TITLE
Unreadable Trust Anchor Locator

### ISSUE THREAD

**Issue by shappleberry** [dragonresearch/rpki.net#867]
Is there a specific format that the RPKI.net toolkit uses for .tal files? It considers the ripe-ncc.tal file unreadable as well as all externally calling .tal files. The only .tal file it can read is the one generated by the parent.

**Comment by sraustein** [comment]
We implement RFC 7730, which is the IETF Standards Track TAL format.

**Comment by shappleberry** [comment]
There's another IETF Standards Track TAL format: RFC 6490. Is there an advantage to 7730 over 6490?

**Comment by shappleberry** [comment]
Thank you! This was good to know. My TAL files are readable now.
