### ISSUE TITLE
cd  ca;make all-tests

### ISSUE THREAD

**Issue by championdot** [dragonresearch/rpki.net#871]
/usr/bin/python xml-parse-test.py
Traceback (most recent call last):
  File "xml-parse-test.py", line 99, in <module>
    parser = rpki.up_down.msg,
AttributeError: 'module' object has no attribute 'msg'
Makefile:56: recipe for target 'parse-test' failed
make[1]: *** [parse-test] Error 1
make[1]: Leaving directory '/home/abc/rpki.net/ca/tests'
Makefile:61: recipe for target 'all-tests' failed
make: *** [all-tests] Error 2

**Comment by sraustein** [comment]
Already fixed (xml-parse-test.py is another obsolete test program, removed).
